# es6中Promise异步编程语法的使用

在es6中promise是一个非常重要和好用的方法    

Promise是异步编程的一种解决方案

> 考虑一个场景

+ 我们通过url1 从服务器加载一个数据data1,data1中包含了下一个请求url2
+ 我们需要从data1中取出url2，从服务器加载数据data2，data2中包含下一个请求url3。
+ 从data2中取出url3 ，发送url3从服务器加载data3，返回最终的数据data3

```javascript
$.ajax("url1",(data1)=>{//192.168.1.1

	console.log("处理第一次请求");

	....存在有100行处理代码

	$.ajax(data1['url2'],(data2)=>{ //192.168.1.2
        
		console.log("处理第二次请求");

		...很多处理代码

		$.ajax(data2['url3'], (data3)=>{//192.168.1.3

			console.log("处理第三次请求");

		})

	})

})
```



这样的代码请求，正常情况下，不会有任何问题，并且可以正常运行并获取我们想要的结果。  

但是这种代码会显得难看，而且不容易维护  

所以我们需要一种更加优雅(便于维护)的方式来解决这个问题



注意：`优雅`的代码，不一定是代码少，而是更加容易维护,更容易让人缕清思路



## Promise的基本使用

> 基本使用方式

```javascript
new Promise((resolve,reject)=>{//resolve和reject 也都是函数
	setTimeout(()=>{
		let data1 = "Promise第一次请求";
		//数据成功  ----> then()
		resolve(data1) //执行处理数据
		//数据失败  ---->catch()
		//reject("Promise中的catch方法执行:err")
	},7000)
}).then(data=>{// 第二次处理代码then()
	console.log(data);
}).catch(err => {
	console.log(err);
    //New Promise()  可以继续使用
})
```



+ Promise 到底做了什么？
  + new Promise创建了一个Promise`对象`实例
  + 小括号中的参数((resolve,reject)=>{})是一个es6函数,
    + resolve和reject也是函数,通常情况下，我们会更具请求数据的成功和失败决定调用哪个函数
  + 成功or失败
    + 请求成功，我们通常会调用resolve(message),这个时候，我们后续的then 会被回调
    + 请求失败，我们通常会调用reject(err)，这个时候，我们后续的catch会被回调
  + then和catch
    + then回调函数,指前一次调用resolve()的回调
    + catch回调函数,指前一次调用reject()的回调



> 异步操作的三种状态

+ 1.pending:等待状态，比如正在进行网络请求，或者定时器还没到时间
  + new Promise((resolve,reject)=>{ ........等待状态.......})
+ 2.fulfill:满足状态，在等待产生结果后，当我们主动回调了 resolve(message)时，就处于满足状态，并且会回调.then((message)=>{})方法
+ 3.reject:拒绝状态，在等待产生结果后，当我们主动调用了reject(err)时，就处于拒绝状态，并且会回调.catch((err)=>{})方法



## Promise的链式调用

> 链式调用 Promise.resolve() 和Promise.reject()

```javascritp
new Promise((resolve,reject)=>{
	setTimeout(()=>{
		let data1 = "hello Promise";
		resolve(data1) //执行处理数据
	},7000)
}).then(data=>{
	console.log(data);// hello Promise
	return Promise.resolve(data + "1111")
}).then(data=>{
	console.log(data);// hello Promise1111
	return Promise.resolve(data + "2222")
}).then(data=>{
	console.log(data);// hello Promise11112222
	return Promise.rejcet( data + "错误")	
}).then(data=>{// 此行不会执行
	console.log(data);
	return Promise.resolve("Promise第二次请求")
}).catch(err => {
	console.log(err);//hello Promise11112222错误
	return Promise.resolve(err+ "aaaa")
}).then(data=>{
	console.log(data);//hello Promise11112222错误aaaa
}).catch(err => {
	console.log(err);
})

```



在对Promise对象进行处理的时候，我们会将数据包装成Promise对象,那么此时我们就可以直接使用Promise.resolve()和Promise.reject()函数





> 链式调用简写

如果我们希望数据直接包装秤Promise.resolve(),那么在then中可以直接返回数据

```javascript
new Promise((resolve,reject)=>{
	setTimeout(()=>{
		let data1 = "hello Promise";
		resolve(data1) //执行处理数据
	},7000)
}).then(data=>{
	console.log(data);// hello Promise
	return data + "1111"
}).then(data=>{
	console.log(data);// hello Promise1111
	return data + "2222"
}).then(data=>{
	console.log(data);// hello Promise11112222
	return Promise.rejcet( data + "错误")	
}).then(data=>{// 此行不会执行
	console.log(data);
	return "Promise第二次请求"
}).catch(err => {
	console.log(err);//hello Promise11112222错误
	return err+ "aaaa"
}).then(data=>{
	console.log(data);//hello Promise11112222错误aaaa
}).catch(err => {
	console.log(err);
})

```

